[data]
data_root = "data/BCCD_processado"

[training]
epochs = 50
batch_size = 1
num_workers = 0
seed = 42
augment = false
# device = "cuda"

[augmentation]
strategies = []

[optimizer]
lr = 0.01
momentum = 0.99
weight_decay = 0.0

[scheduler]
use_scheduler = false
step_size = 10
gamma = 0.5

[output]
output_dir = "runs/unet_no_aug"
checkpoint_every = 5
final_model_name = "unet_final.pth"
